// src/components/simple/Card/index.svelte
<script>
	export let h = false;
	export let mb0 = false;
	export let hover = false;
	export let compact = false;
	export let fullHeight = false;
</script>

<div
	class:mb0
	class:hover
	class:compact
	class:full-height={fullHeight}
	class:vertical={!h}
	class:horizontal={h}
	class="flex radius"
>
	<slot />
</div>

<style src="./styles.css"></style>

// components/simple/Card/index.tsx
import { FC } from 'react';
import './styles.module.css';

interface CardProps {
  h?: boolean;
  mb0?: boolean;
  hover?: boolean;
  compact?: boolean;
  fullHeight?: boolean;
  children?: React.ReactNode;
}

const Card: FC<CardProps> = ({
  h = false,
  mb0 = false,
  hover = false,
  compact = false,
  fullHeight = false,
  children,
}) => {
  const classes = `
        flex
        radius
        ${mb0 ? 'mb0' : ''}
        ${hover ? 'hover' : ''}
        ${compact ? 'compact' : ''}
        ${fullHeight ? 'full-height' : ''}
        ${h ? 'horizontal' : 'vertical'}
    `;

  return <div className={classes.trim()}>{children}</div>;
};

export default Card;
