// src/components/complex/ContentCard.svelte
<script>
	import Avatar from '../simple/Avatar.svelte';
	import Card from '../simple/Card.svelte';

	export let link = '';
	export let name = '';
	export let imageSrc = '';
	export let imageSrcSet = '';
	export let imageStyle = '';
</script>

<a href={link || '#'} target="_blank">
	<Card mb0 hover>
		<div class="flex direction-column justify-center align-center">
			<Avatar {imageSrc} {imageSrcSet} {imageStyle} />
			<span>{name || 'Unspecified'}</span>
		</div>
	</Card>
</a>

<style>
	.flex {
		gap: 1rem;
	}
	a {
		display: block;
		width: 140px;
	}
</style>

// components/ui/compound/content-card.tsx
import { Card } from '@/components/ui/simple/card';
import { Flex } from '@/components/ui/simple/flex';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/simple/avatar';

interface ContentCardProps {
  link?: string;
  name?: string;
  imageSrc: string;
}

const ContentCard: React.FC<ContentCardProps> = ({
  link = '#',
  name = 'Unspecified',
  imageSrc,
}) => {
  const abbr = name.charAt(0).toUpperCase();

  return (
    <a href={link} target="_blank">
      <Card>
        <Flex direction="column" justify="center" align="center">
          <Avatar>
            <AvatarImage src={imageSrc} alt={abbr} />
            <AvatarFallback>{abbr}</AvatarFallback>
          </Avatar>
          <span>{name}</span>
        </Flex>
      </Card>

      <style jsx>{`
        a {
          display: block;
          width: 140px;
        }
      `}</style>
    </a>
  );
};

export { ContentCard };
