// src/components/complex/Tabs/Companies.svelte
<script>
	import ContentRow from '../ContentRow.svelte';
</script>

<ContentRow
	url="/images/preply.png"
	rightText="Preply, Barcelona 🇪🇸"
	leftText="Senior Software Engineer"
/>
<ContentRow
	url="/images/tf961.jpeg"
	rightText="TF961, Lebanon 🇱🇧"
	leftText="Senior Software Engineer"
/>
<ContentRow
	url="/images/fibler.jpeg"
	rightText="Fibler, Lebanon 🇱🇧"
	leftText="Software Engineer"
/>

// components/compound/Tabs/Companies.tsx
import ContentRow from '../ContentRow';

const Component = () => (
  <>
    <ContentRow
      url="/images/preply.png"
      rightText="Preply, Barcelona 🇪🇸"
      leftText="Senior Software Engineer"
    />
    <ContentRow
      url="/images/tf961.jpeg"
      rightText="TF961, Lebanon 🇱🇧"
      leftText="Senior Software Engineer"
    />
    <ContentRow
      url="/images/fibler.jpeg"
      rightText="Fibler, Lebanon 🇱🇧"
      leftText="Software Engineer"
    />
  </>
);

export default Component;
