// src/components/complex/ContentCard.svelte
<script>
	import Avatar from '../simple/Avatar.svelte';
	import Card from '../simple/Card.svelte';

	export let link = '';
	export let name = '';
	export let imageSrc = '';
	export let imageSrcSet = '';
	export let imageStyle = '';
</script>

<a href={link || '#'} target="_blank">
	<Card mb0 hover>
		<div class="flex direction-column justify-center align-center">
			<Avatar {imageSrc} {imageSrcSet} {imageStyle} />
			<span>{name || 'Unspecified'}</span>
		</div>
	</Card>
</a>

<style>
	.flex {
		gap: 1rem;
	}
	a {
		display: block;
		width: 140px;
	}
</style>

// components/compound/ContentCard/index.tsx
import { CSSProperties } from 'react';
import Card from '@/components/simple/Card';
import Avatar from '@/components/simple/Avatar';
import Flex from '@/components/simple/Flex';

interface ContentCardProps {
  link?: string;
  name?: string;
  imageSrc: string;
  imageStyle?: CSSProperties;
}

const ContentCard: React.FC<ContentCardProps> = ({
  link = '#',
  name = 'Unspecified',
  imageSrc,
  imageStyle,
}) => {
  return (
    <a href={link} target="_blank">
      <Card mb0 hover>
        <Flex direction="column" justify="center" align="center">
          <Avatar imageSrc={imageSrc} imageStyle={imageStyle} />
          <span>{name}</span>
        </Flex>
      </Card>

      <style jsx>{`
        a {
          display: block;
          width: 140px;
        }
      `}</style>
    </a>
  );
};

export default ContentCard;
