// components/simple/TabView/index.tsx
import React, { FC, useState } from 'react';
import './styles.module.css';

type Tab = {
  name: string;
  component: React.ElementType;
};

interface TabsProps {
  tabs: Tab[];
}

const Tabs: FC<TabsProps> = ({ tabs = [] }) => {
  const [selected, setSelected] = useState(0);

  return (
    <div>
      <div className="wrapper flex justify-space-between align-center radius">
        {tabs.map((tab, i) => (
          <div
            key={i}
            className={`flex justify-center align-center radius ${
              selected === i ? 'selected' : ''
            }`}
            onClick={() => setSelected(i)}
          >
            {tab.name}
          </div>
        ))}
      </div>
      {tabs.length > 0 && React.createElement(tabs[selected].component)}
    </div>
  );
};

export default Tabs;

// src/components/simple/TabView/index.svelte
<script lang="ts">
	type Tab = {
		name: string;
		component: any;
	};

	export let tabs: Tab[] = [];

	let selected = 0;
</script>

<div class="wrapper flex justify-space-between align-center radius">
	{#each tabs as tab, i}
		<div
			class="flex justify-center align-center radius"
			class:selected={selected === i}
			on:click={() => (selected = i)}
		>
			{tab.name}
		</div>
	{/each}
</div>
<svelte:component this={tabs[selected].component} />

<style src="./styles.css"></style>
